#!/usr/bin/env bash
#
# Setup wizard for the Marginalia sign-in flow.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Marginalia sign-in setup"

# ── Stage 1: Confirm the project ref and grab the live URL/anon key ───────
stage "Confirm Supabase project + capture .env values"
say "This wizard configures sign-in for the live Supabase project: PROJECT_REF."
say "It will write your project's URL and anon key into .env so the app can talk to it."
open_url "https://supabase.com/dashboard/project/PROJECT_REF/settings/api"
step "On the API Settings page, find 'Project URL' and 'Project API keys → anon public'."
step "Copy the Project URL (it looks like https://PROJECT_REF.supabase.co)."
ask VITE_SUPABASE_URL "Paste the Project URL:"
step "Copy the anon public key (a long string starting with 'eyJ...')."
ask VITE_SUPABASE_ANON "Paste the anon public key:"
write_env VITE_SUPABASE_URL  "$VITE_SUPABASE_URL"
write_env VITE_SUPABASE_ANON "$VITE_SUPABASE_ANON"

# ── Stage 2: Enable Email sign-in (no extra setup needed) ──────────────────
stage "Enable Email sign-in provider in Supabase"
say "Email sign-in is the default. Just turn it on; no external accounts needed."
open_url "https://supabase.com/dashboard/project/PROJECT_REF/auth/providers"
step "Find 'Email' in the providers list and toggle it ON (it usually already is)."
step "Toggle OFF 'Confirm email' for now — easier to test locally. (You can re-enable it before going public.)"
step "Click 'Save'."
pause "Done? (Saved)"

# ── Stage 3: Google OAuth — get a Client ID + Secret from Google Cloud ────
stage "Google OAuth — create an OAuth client"
say "You need a Google Cloud project + an OAuth client. This is the part I can't do for you — Google issues these to your Google account."
open_url "https://console.cloud.google.com/auth/clients/create"
note "If you've never used Google Cloud Console: pick or create a project first at"
note "https://console.cloud.google.com/projectcreate — name it anything (e.g. 'Marginalia')."
step "On the OAuth client create screen, choose 'Web application' as the Application type."
step "Name: 'Marginalia' (or anything)."
step "Under 'Authorized JavaScript origins', click '+ Add URI' and paste BOTH:"
note "    - https://PROJECT_REF.supabase.co"
note "    - http://localhost:5173  (for local dev)"
step "Under 'Authorized redirect URIs', click '+ Add URI' and paste BOTH:"
note "    - https://PROJECT_REF.supabase.co/auth/v1/callback"
note "    - http://localhost:54321/auth/v1/callback  (only if you run Supabase locally — skip if unsure)"
step "Click 'Create'. A modal will show your Client ID and Client Secret."
ask_secret GOOGLE_CLIENT_ID "Paste the Google Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Google Client Secret:"

# ── Stage 4: GitHub OAuth — get a Client ID + Secret from GitHub ──────────
stage "GitHub OAuth — create an OAuth app"
say "Same idea, GitHub side. One-time setup, takes about a minute."
open_url "https://github.com/settings/applications/new"
step "Application name: 'Marginalia'."
step "Homepage URL: 'https://PROJECT_REF.supabase.co' (or your deployed app URL)."
step "Authorization callback URL: 'https://PROJECT_REF.supabase.co/auth/v1/callback'"
step "Click 'Register application'."
step "On the next page, copy the 'Client ID'."
ask_secret GITHUB_CLIENT_ID "Paste the GitHub Client ID:"
step "Click 'Generate a new client secret'. Copy it (you'll only see it once)."
ask_secret GITHUB_CLIENT_SECRET "Paste the GitHub Client Secret:"

# ── Stage 5: Paste the OAuth credentials into Supabase ────────────────────
stage "Wire Google + GitHub into Supabase"
say "Now we'll register those four secrets with Supabase so sign-in works."
open_url "https://supabase.com/dashboard/project/PROJECT_REF/auth/providers"
note "We'll do this in the Supabase SQL editor so it's reproducible and you can audit it later."
open_url "https://supabase.com/dashboard/project/PROJECT_REF/sql/new"
say "Paste the following SQL (values already filled in) and click 'Run':"
cat <<SQL
  -- Enable Google provider
  update auth.providers
     set config = jsonb_set(
       coalesce(config, '{}'::jsonb),
       '{client_id}',
       to_jsonb('$GOOGLE_CLIENT_ID'::text)
     )
   where name = 'google';
  update auth.providers
     set config = jsonb_set(config, '{secret}', to_jsonb('$GOOGLE_CLIENT_SECRET'::text))
   where name = 'google';

  -- Enable GitHub provider
  update auth.providers
     set config = jsonb_set(coalesce(config, '{}'::jsonb), '{client_id}', to_jsonb('$GITHUB_CLIENT_ID'::text))
   where name = 'github';
  update auth.providers
     set config = jsonb_set(config, '{secret}', to_jsonb('$GITHUB_CLIENT_SECRET'::text))
   where name = 'github';

  -- Flip both providers on
  update auth.providers set enabled = true where name in ('google', 'github');
SQL
warn "Note: the above assumes the providers already exist as rows. On Supabase, you usually"
warn "need to enable the provider in the Dashboard UI first (toggles in the providers list)"
warn "so the row is created. If 'Run' says 0 rows updated, go back to the Providers page,"
warn "click Google, paste the Client ID + Secret, click Save; same for GitHub."
pause "Saved (via SQL or Dashboard)?"

# ── Stage 6: Set the Supabase Site URL + Redirect URLs ────────────────────
stage "Configure Supabase URL settings"
say "This tells Supabase which URLs to redirect to after sign-in. Without it, the post-OAuth callback fails."
open_url "https://supabase.com/dashboard/project/PROJECT_REF/auth/url-configuration"
step "Site URL: set to the URL you'll deploy the app at. For local dev: 'http://localhost:5173'."
step "Click '+ Add URL' under Redirect URLs and add:"
note "    - http://localhost:5173      (dev)"
note "    - http://localhost:5173/**   (dev, with wildcards)"
note "    - https://your-deployed-app.com   (wherever you deploy, when you deploy)"
step "Click 'Save'."
pause "Done? (Saved)"

finish
